version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "7500:3000"
    volumes:
      - /home/node/app/node_modules
      - ./:/home/node/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=7500
  
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - ./:/home/node/app
    command: ["npm", "run", "test"]
    
